### ISSUE TITLE
Geen up-to-date info

### ISSUE THREAD

**Issue by Simanias** [Xorfor/HA-Windcentrale#1]
Bedankt voor de sensor @Xorfor, ik had deze in een soortgelijke configuratie ook, maar deze is net wat uitgebreider.
Helaas werken een hoop van de molens niet meer, aangezien er een probleem is met de server van de windcentrale.
Als je kijkt op:
https://zep-api.windcentrale.nl/production/121/live
zie je dat de timestamp van 31-5 is. Ik heb een aantal andere molens bekeken en alleen id 1 en 2 doen het.

**Comment by Xorfor** [comment]
@Simanias 
Ik heb inderdaad gezien, dat bij mij idd 1 andere molen (ook de Trouwe Wachter) het sinds een paar weken het niet deed. Ik heb dit voorgelegd aan de Windcentrale en deze vertelden, dat er idd problemen zijn met de data. Er schijnt een nieuwe oplossing te komen. Op windcentrale.nl werkt het ook niet! In de app gaat het wel goed. Ik ben aan het kijken hoe ik die interface kan gebruiken!

**Comment by Simanias** [comment]
Okey duidelijk, ik wacht het af.

**Comment by Xorfor** [comment]
Ik heb een manier gevonden die voor alle windmolens de data kan ophalen. Niet real-time in Watt, maar wel wat er aan kWh geleverd wordt. Ik ben het nu aan het testen, ook hoe het met apexcharts-card getoond kan worden. Het testen gaat nu lastig want het is nagenoeg windstil 😄

**Comment by Xorfor** [comment]
Windmills are sending data again and new energy sensor is working. I will close this issue.

**Comment by Simanias** [comment]
Ja ik zag het ook alweer, super!
